---
- hosts: ansible-controller
  become: true

  vars_files:
    - ../credentials.yml

  tasks:
    - name: Install required packages
      yum:
        name:
          - yum-utils
          - createrepo
          - httpd
          - git

    - name: Sync packages
      command: reposync -lgm --repoid={{ item }} --download_path=/var/www/html/repos
      with_items: "{{ redhat_repos }}"

    - name: Create repos for packages
      command: createrepo /var/www/html/repos/{{ item }} -o /var/www/html/repos/{{ item }}
      with_items: "{{ redhat_repos }}"

    - name: Set permissions for packages
      file:
        recurse: true
        path: /var/www/html/repos
        mode: o+r

    - name: Restore context
      command: restorecon -vR /var/www/html

    - name: Open firewall
      firewalld:
        service: http
        permanent: true
        state: enabled

    - name: Start and enable httpd
      systemd:
        name: httpd
        enabled: true
        state: started
