---
- hosts: ansible-controller
  become: true

  vars_files:
    - ../credentials.yml

  tasks:
    - name: Install required packages
      yum:
        name:
          - python2-pip
          - docker-1.13.1

    - name: Install pip packages
      pip:
        name: docker

    - name: Start and enable docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Login to registry
      docker_login:
          username: "{{ redhat_username }}"
          password: "{{ redhat_password }}"
          registry_url: registry.redhat.io

    - name: Pull image with private registry
      docker_image:
        name: registry:2

    - name: Run docker registry
      docker_container:
        name: registry
        state: present
        image: registry:2
        restart_policy: always
        published_ports:
          - "5000:5000"

    - name: Add insecure registries
      template:
        src: templates/etc/docker/daemon.json.j2
        dest: /etc/docker/daemon.json

    - name: Restart docker
      systemd:
        name: docker
        state: restarted
        daemon_reload: true

    - name: Pull and retag docker images
      docker_image:
        name: "registry.redhat.io/{{ item.name }}"
        repository: "{{ docker_registry_ip }}:5000/{{ item.name }}"
        tag: "{{ item.tag }}"
        push: true
      with_items: "{{ openshift_docker_images }}"
    
    - name: Retag openshift images
      docker_image:
        name: "registry.redhat.io/{{ item.name }}"
        repository: "{{ docker_registry_ip }}:5000/{{ item.name }}"
        tag: "{{ item.major_tag }}"
        push: true
      with_items: "{{ openshift_docker_images}}"
      when: item.major_tag | default(false)

    - name: Open firewall
      firewalld:
        port: 5000/tcp
        permanent: true
        state: enabled
