---
- hosts: ansible-controller
  become: true

  vars_files:
    - ../credentials.yml

  tasks:
    - name: Install required packages
      yum:
        name:
          - python2-pip
          - docker-1.13.1

    - name: Install pip packages
      pip:
        name: docker

    - name: Start and enable docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Login to registry
      docker_login:
          username: "{{ redhat_username }}"
          password: "{{ redhat_password }}"
          registry_url: registry.redhat.io
    
    - name: Add insecure registry
      

    - name: Pull image with private registry
      docker_image:
        name: registry:2

    - name: Run docker registry
      docker_container:
        name: registry
        image: registry:2
        restart_policy: always
        published_ports:
          - "5000:5000"

    - name: Pull and retag docker images
      docker_image:
        name: "registry.redhat.io/{{ item.name }}"
        repository: "{{ docker_registry_ip }}:5000/{{ item.name }}"
        tag: "{{ item.tag | default('v3.11.16') }}"
        push: true
      with_items:
      # Required
        - name: openshift3/apb-base
        - name: openshift3/apb-tools
        - name: openshift3/automation-broker-apb
        - name: openshift3/csi-attacher
        - name: openshift3/csi-driver-registrar
        - name: openshift3/csi-livenessprobe
        - name: openshift3/csi-provisioner
        - name: openshift3/grafana
        - name: openshift3/image-inspector
        - name: openshift3/mariadb-apb
        - name: openshift3/mediawiki
        - name: openshift3/mediawiki-apb
        - name: openshift3/mysql-apb
        - name: openshift3/ose-ansible
        - name: openshift3/ose-ansible-service-broker
        - name: openshift3/ose-cli
        - name: openshift3/ose-cluster-autoscaler
        - name: openshift3/ose-cluster-capacity
        - name: openshift3/ose-cluster-monitoring-operator
        - name: openshift3/ose-console
        - name: openshift3/ose-configmap-reloader
        - name: openshift3/ose-control-plane
        - name: openshift3/ose-deployer
        - name: openshift3/ose-descheduler
        - name: openshift3/ose-docker-builder
        - name: openshift3/ose-docker-registry
        - name: openshift3/ose-efs-provisioner
        - name: openshift3/ose-egress-dns-proxy
        - name: openshift3/ose-egress-http-proxy
        - name: openshift3/ose-egress-router
        - name: openshift3/ose-haproxy-router
        - name: openshift3/ose-hyperkube
        - name: openshift3/ose-hypershift
        - name: openshift3/ose-keepalived-ipfailover
        - name: openshift3/ose-kube-rbac-proxy
        - name: openshift3/ose-kube-state-metrics
        - name: openshift3/ose-metrics-server
        - name: openshift3/ose-node
        - name: openshift3/ose-node-problem-detector
        - name: openshift3/ose-operator-lifecycle-manager
        - name: openshift3/ose-pod
        - name: openshift3/ose-prometheus-config-reloader
        - name: openshift3/ose-prometheus-operator
        - name: openshift3/ose-recycler
        - name: openshift3/ose-service-catalog
        - name: openshift3/ose-template-service-broker
        - name: openshift3/ose-web-console
        - name: openshift3/postgresql-apb
        - name: openshift3/registry-console
        - name: openshift3/snapshot-controller
        - name: openshift3/snapshot-provisioner
        - name: rhel7/etcd
          tag: 3.2.22

        # Optional
        - name: openshift3/metrics-cassandra
        - name: openshift3/metrics-hawkular-metrics
        - name: openshift3/metrics-hawkular-openshift-agent
        - name: openshift3/metrics-heapster
        - name: openshift3/oauth-proxy
        - name: openshift3/ose-logging-curator5
        - name: openshift3/ose-logging-elasticsearch5
        - name: openshift3/ose-logging-eventrouter
        - name: openshift3/ose-logging-fluentd
        - name: openshift3/ose-logging-kibana5
        - name: openshift3/ose-metrics-schema-installer
        - name: openshift3/prometheus
        - name: openshift3/prometheus-alert-buffer
        - name: openshift3/prometheus-alertmanager
        - name: openshift3/prometheus-node-exporter

        - name: cloudforms46/cfme-openshift-postgresql
          tag: latest
        - name: cloudforms46/cfme-openshift-memcached
          tag: latest
        - name: cloudforms46/cfme-openshift-app-ui
          tag: latest
        - name: cloudforms46/cfme-openshift-app
          tag: latest
        - name: cloudforms46/cfme-openshift-embedded-ansible
          tag: latest
        - name: cloudforms46/cfme-openshift-httpd
          tag: latest
        - name: cloudforms46/cfme-httpd-configmap-generator
          tag: latest

        # S2I
        - name: jboss-amq-6/amq63-openshift
        - name: jboss-datagrid-7/datagrid71-openshift
        - name: jboss-datagrid-7/datagrid71-client-openshift
        - name: jboss-datavirt-6/datavirt63-openshift
        - name: jboss-datavirt-6/datavirt63-driver-openshift
        - name: jboss-decisionserver-6/decisionserver64-openshift
        - name: jboss-processserver-6/processserver64-openshift
        - name: jboss-eap-6/eap64-openshift
        - name: jboss-eap-7/eap70-openshift
        - name: jboss-webserver-3/webserver31-tomcat7-openshift
        - name: jboss-webserver-3/webserver31-tomcat8-openshift
        - name: openshift3/jenkins-2-rhel7
        - name: openshift3/jenkins-agent-maven-35-rhel7
        - name: openshift3/jenkins-agent-nodejs-8-rhel7
        - name: openshift3/jenkins-slave-base-rhel7
        - name: openshift3/jenkins-slave-maven-rhel7
        - name: openshift3/jenkins-slave-nodejs-rhel7
        - name: rhscl/mongodb-32-rhel7
        - name: rhscl/mysql-57-rhel7
        - name: rhscl/perl-524-rhel7
        - name: rhscl/php-56-rhel7
        - name: rhscl/postgresql-95-rhel7
        - name: rhscl/python-35-rhel7
        - name: redhat-sso-7/sso70-openshift
        - name: rhscl/ruby-24-rhel7
        - name: redhat-openjdk-18/openjdk18-openshift
        - name: redhat-sso-7/sso71-openshift
        - name: rhscl/nodejs-6-rhel7
        - name: rhscl/mariadb-101-rhel7
