---
- hosts: ansible-controller
  vars_files:
    - ../credentials.yml

  tasks:
 
    - name: Install required packages
      become: true
      yum:
        name:
          - docker

    - name: Pull docker images
      with_items:
        # Required
        - docker pull registry.redhat.io/openshift3/apb-base:v3.11.16
        - docker pull registry.redhat.io/openshift3/apb-tools:v3.11.16
        - docker pull registry.redhat.io/openshift3/automation-broker-apb:v3.11.16
        - docker pull registry.redhat.io/openshift3/csi-attacher:v3.11.16
        - docker pull registry.redhat.io/openshift3/csi-driver-registrar:v3.11.16
        - docker pull registry.redhat.io/openshift3/csi-livenessprobe:v3.11.16
        - docker pull registry.redhat.io/openshift3/csi-provisioner:v3.11.16
        - docker pull registry.redhat.io/openshift3/grafana:v3.11.16
        - docker pull registry.redhat.io/openshift3/image-inspector:v3.11.16
        - docker pull registry.redhat.io/openshift3/mariadb-apb:v3.11.16
        - docker pull registry.redhat.io/openshift3/mediawiki:v3.11.16
        - docker pull registry.redhat.io/openshift3/mediawiki-apb:v3.11.16
        - docker pull registry.redhat.io/openshift3/mysql-apb:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-ansible:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-ansible-service-broker:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-cli:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-cluster-autoscaler:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-cluster-capacity:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-cluster-monitoring-operator:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-console:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-configmap-reloader:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-control-plane:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-deployer:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-descheduler:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-docker-builder:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-docker-registry:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-efs-provisioner:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-egress-dns-proxy:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-egress-http-proxy:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-egress-router:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-haproxy-router:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-hyperkube:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-hypershift:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-keepalived-ipfailover:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-kube-rbac-proxy:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-kube-state-metrics:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-metrics-server:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-node:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-node-problem-detector:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-operator-lifecycle-manager:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-pod:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-prometheus-config-reloader:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-prometheus-operator:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-recycler:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-service-catalog:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-template-service-broker:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-web-console:v3.11.16
        - docker pull registry.redhat.io/openshift3/postgresql-apb:v3.11.16
        - docker pull registry.redhat.io/openshift3/registry-console:v3.11.16
        - docker pull registry.redhat.io/openshift3/snapshot-controller:v3.11.16
        - docker pull registry.redhat.io/openshift3/snapshot-provisioner:v3.11.16
        - docker pull registry.redhat.io/rhel7/etcd:3.2.22

        # Optional
        - docker pull registry.redhat.io/openshift3/metrics-cassandra:v3.11.16
        - docker pull registry.redhat.io/openshift3/metrics-hawkular-metrics:v3.11.16
        - docker pull registry.redhat.io/openshift3/metrics-hawkular-openshift-agent:v3.11.16
        - docker pull registry.redhat.io/openshift3/metrics-heapster:v3.11.16
        - docker pull registry.redhat.io/openshift3/oauth-proxy:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-logging-curator5:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-logging-elasticsearch5:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-logging-eventrouter:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-logging-fluentd:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-logging-kibana5:v3.11.16
        - docker pull registry.redhat.io/openshift3/ose-metrics-schema-installer:v3.11.16
        - docker pull registry.redhat.io/openshift3/prometheus:v3.11.16
        - docker pull registry.redhat.io/openshift3/prometheus-alert-buffer:v3.11.16
        - docker pull registry.redhat.io/openshift3/prometheus-alertmanager:v3.11.16
        - docker pull registry.redhat.io/openshift3/prometheus-node-exporter:v3.11.16
        - docker pull registry.redhat.io/cloudforms46/cfme-openshift-postgresql
        - docker pull registry.redhat.io/cloudforms46/cfme-openshift-memcached
        - docker pull registry.redhat.io/cloudforms46/cfme-openshift-app-ui
        - docker pull registry.redhat.io/cloudforms46/cfme-openshift-app
        - docker pull registry.redhat.io/cloudforms46/cfme-openshift-embedded-ansible
        - docker pull registry.redhat.io/cloudforms46/cfme-openshift-httpd
        - docker pull registry.redhat.io/cloudforms46/cfme-httpd-configmap-generator

        # S2I
        - docker pull registry.redhat.io/jboss-amq-6/amq63-openshift:v3.11.16
        - docker pull registry.redhat.io/jboss-datagrid-7/datagrid71-openshift:v3.11.16
        - docker pull registry.redhat.io/jboss-datagrid-7/datagrid71-client-openshift:v3.11.16
        - docker pull registry.redhat.io/jboss-datavirt-6/datavirt63-openshift:v3.11.16
        - docker pull registry.redhat.io/jboss-datavirt-6/datavirt63-driver-openshift:v3.11.16
        - docker pull registry.redhat.io/jboss-decisionserver-6/decisionserver64-openshift:v3.11.16
        - docker pull registry.redhat.io/jboss-processserver-6/processserver64-openshift:v3.11.16
        - docker pull registry.redhat.io/jboss-eap-6/eap64-openshift:v3.11.16
        - docker pull registry.redhat.io/jboss-eap-7/eap70-openshift:v3.11.16
        - docker pull registry.redhat.io/jboss-webserver-3/webserver31-tomcat7-openshift:v3.11.16
        - docker pull registry.redhat.io/jboss-webserver-3/webserver31-tomcat8-openshift:v3.11.16
        - docker pull registry.redhat.io/openshift3/jenkins-2-rhel7:v3.11.16
        - docker pull registry.redhat.io/openshift3/jenkins-agent-maven-35-rhel7:v3.11.16
        - docker pull registry.redhat.io/openshift3/jenkins-agent-nodejs-8-rhel7:v3.11.16
        - docker pull registry.redhat.io/openshift3/jenkins-slave-base-rhel7:v3.11.16
        - docker pull registry.redhat.io/openshift3/jenkins-slave-maven-rhel7:v3.11.16
        - docker pull registry.redhat.io/openshift3/jenkins-slave-nodejs-rhel7:v3.11.16
        - docker pull registry.redhat.io/rhscl/mongodb-32-rhel7:v3.11.16
        - docker pull registry.redhat.io/rhscl/mysql-57-rhel7:v3.11.16
        - docker pull registry.redhat.io/rhscl/perl-524-rhel7:v3.11.16
        - docker pull registry.redhat.io/rhscl/php-56-rhel7:v3.11.16
        - docker pull registry.redhat.io/rhscl/postgresql-95-rhel7:v3.11.16
        - docker pull registry.redhat.io/rhscl/python-35-rhel7:v3.11.16
        - docker pull registry.redhat.io/redhat-sso-7/sso70-openshift:v3.11.16
        - docker pull registry.redhat.io/rhscl/ruby-24-rhel7:v3.11.16
        - docker pull registry.redhat.io/redhat-openjdk-18/openjdk18-openshift:v3.11.16
        - docker pull registry.redhat.io/redhat-sso-7/sso71-openshift:v3.11.16
        - docker pull registry.redhat.io/rhscl/nodejs-6-rhel7:v3.11.16
        - docker pull registry.redhat.io/rhscl/mariadb-101-rhel7:v3.11.16