---
- hosts: ansible-controller
  vars_files:
    - ../credentials.yml

  tasks:
    - name: Install required packages
      become: true
      yum:
        name:
          - yum-utils
          - createrepo
          - nginx
          - git

    - name: Create directory to serve repos
      file:
        state: directory
        path: /tmp/repos

    - name: Sync packages
      become: true
      command: reposync -lgm --repoid={{ item }} --download_path=/usr/share/nginx/html/repos
      with_items: "{{ redhat_repos }}"

    - name: Create repos for packages
      become: true
      command: createrepo -v  -o /usr/share/nginx/html/repos/{{ item }}
      with_items: "{{ redhat_repos }}"

    - name: Open firewall
      become: true
      firewalld:
        service: http
        permanent: true
        state: enabled

    - name: Enable nginx
      become: true
      systemd:
        name: nginx
        state: enabled

    - name: Start nginx
      become: true
      systemd:
        name: nginx
        state: started
