---
# Generate inventory
- hosts: ansible-controller
  become: true

  tasks:
    - name: Install openshift-ansible
      yum:
        name: openshift-ansible
        state: present

    - name: Generate inventory file
      template:
        src: templates/etc/ansible/hosts.j2
        dest: /etc/ansible/hosts
