---
# Manage subscription
- hosts: ansible-controller
  become: true

  vars_files:
    - "{{ inventory_dir }}/credentials.yml"
    - "{{ inventory_dir }}/vars.yml"

  tasks:
    - name: Install subscription-manager
      yum:
        name: subscription-manager
        state: present

    - name: Enable registration
      redhat_subscription:
        state: present
        username: "{{ redhat_username }}"
        password: "{{ redhat_password }}"
        auto_attach: false

