all:
  hosts:
    ansible-controller:
      localhost:
        vars:
          ansible_connection: local
          ansible_python_interpreter: "{{ansible_playbook_python}}"
  children:
    openshift:
      hosts:
        ${openshift_master_fqdn}:
        ${openshift_node_1_fqdn}:
        ${openshift_node_2_fqdn}:
